### ISSUE TITLE
can not get the token when request

### ISSUE THREAD

**Issue by yanxinorg** [wso2/carbon-device-mgt-plugins#639]
components/device-types/androidsense-plugin/org.wso2.carbon.device.mgt.iot.androidsense.agent/app/src/main/java/org/wso2/carbon/iot/android/sense/util/dto/TokenIssuerService.java

is there missing the prefix “/oauth2” of the code "  @Path("/token")  "

**Comment by ayyoob** [comment]
I believe you might have entered https-9443/http-9763 port but from IoTS 3.0.0, the calls goes through the gateway which is only "/token". Default gateway port is https - 8243/http-8280.

**Comment by yanxinorg** [comment]
Thanks for your reply.
I recompile the android sense agent code like what i metioned above. and it work!
And the placeholder text int the editview hints the port is 8243. But i CANNOT register using 8243 for wrong authentication.

Additional.
There are so many hard code to change when i want use a ip replacing localhost  ╮(╯_╰)╭

**Comment by ayyoob** [comment]
If there are many places that has hard coded localhost then it is wrong, could it be possible point out those location ?

**Comment by yanxinorg** [comment]
I mean this guide document page  https://docs.wso2.com/display/IoTS300/Configuring+WSO2+IoT+Server+with+the+IP

And,could you please give me a suggestion how to bind certain ip address when i use two or more ip address.

![test](https://cloud.githubusercontent.com/assets/20394276/25001203/f7343fd8-2076-11e7-8a3f-0cee848ed27c.png)

like above.
my request ip is 192.168.2.141,but when i click [View Device Analytics] ,i redirect to 172.17.0.1(the docker use).

![20170413183147](https://cloud.githubusercontent.com/assets/20394276/25001339/ac9f60e6-2077-11e7-88d8-d62746469719.png)

Thanks a lot!
